# Generated by Django 3.2.8 on 2021-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('kategoria', models.CharField(max_length=20)),
                ('data', models.TimeField()),
                ('ilosc', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
