# Generated by Django 3.2.8 on 2021-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='status',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='available', max_length=32),
        ),
    ]
