# Generated by Django 3.2.8 on 2021-10-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0003_auto_20211019_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='categoty',
            field=models.CharField(choices=[('tak', 'nie')], max_length=50, null=True),
        ),
    ]
