# Generated by Django 3.2.8 on 2021-10-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0004_alter_produkty_categoty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='data',
        ),
        migrations.AddField(
            model_name='produkty',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='categoty',
            field=models.CharField(choices=[('nie', 'nie'), ('tak', 'tak'), ('całkowicie zepsute', 'całkowicie zepsute')], max_length=50, null=True),
        ),
    ]
