# Generated by Django 3.2.8 on 2021-10-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hurtownia', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamówienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.PositiveIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Klijent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hurtownia.produkty')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
