# Generated by Django 3.1.7 on 2021-12-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0008_auto_20211025_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='date_created',
        ),
    ]
