# Generated by Django 3.1.7 on 2021-12-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0009_remove_produkty_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name_plural': 'Produkty'},
        ),
    ]
