# Generated by Django 3.1.7 on 2021-12-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0010_auto_20211202_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkty',
            options={},
        ),
    ]
