# Generated by Django 3.1.7 on 2021-12-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0012_auto_20211208_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='zepsuty',
            new_name='categoty',
        ),
    ]
