# Generated by Django 4.0 on 2021-12-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hurtownia', '0015_alter_produkty_id_alter_zamówienia_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KupnoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('miasto', models.CharField(max_length=200, null=True)),
                ('kodpocztowy', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('klijent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hurtownia.produkty')),
            ],
        ),
    ]
