# Generated by Django 4.0 on 2022-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0016_kupnoaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='cena',
            field=models.FloatField(null=True),
        ),
    ]
