# Generated by Django 4.0 on 2022-01-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0018_rename_categoty_produkty_uszkodzony'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='img',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
