# Generated by Django 4.0 on 2022-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0020_alter_produkty_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='img',
        ),
        migrations.AddField(
            model_name='produkty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
