# Generated by Django 4.0 on 2022-03-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hurtownia', '0023_feedback_zwrot_delete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwrot',
            name='klijent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
