# Generated by Django 4.0 on 2022-03-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0025_remove_zwrot_klijent_alter_zwrot_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
