# Generated by Django 4.0 on 2022-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0027_zwrot_klijent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkty',
            options={'ordering': ('nazwa',)},
        ),
        migrations.AddField(
            model_name='produkty',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterIndexTogether(
            name='produkty',
            index_together={('id', 'slug')},
        ),
    ]
