# Generated by Django 4.0 on 2022-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0028_alter_produkty_options_produkty_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
