# Generated by Django 4.0 on 2022-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0029_produkty_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
