# Generated by Django 4.0 on 2022-04-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0030_alter_produkty_cena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kupnoaddress',
            name='kodpocztowy',
        ),
        migrations.AddField(
            model_name='kupnoaddress',
            name='kod_pocztowy',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
