# Generated by Django 4.0 on 2022-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0031_remove_kupnoaddress_kodpocztowy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupnoaddress',
            name='kod_pocztowy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
