# Generated by Django 4.0 on 2022-04-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurtownia', '0032_alter_kupnoaddress_kod_pocztowy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KupnoAddress',
        ),
    ]
