# Generated by Django 3.1.7 on 2021-11-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211110_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
    ]
