# Generated by Django 3.1.7 on 2021-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211121_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonee',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
